import { eq } from 'drizzle-orm';

import { automationSettings } from '@/lib/db/schema';
import type { TenantDb } from '@/server/api/db';

export async function getAutomationSettings(
  db: TenantDb,
  organizationId: number
) {
  const [settings] = await db
    .select({
      autoGenerateDrafts:
        automationSettings.autoGenerateDrafts
    })
    .from(automationSettings)
    .where(
      eq(
        automationSettings.organizationId,
        organizationId
      )
    )
    .limit(1);

  return {
    autoGenerateDrafts:
      settings?.autoGenerateDrafts ?? false
  };
}

export async function saveAutomationSettings(
  db: TenantDb,
  organizationId: number,
  autoGenerateDrafts: boolean
) {
  await db
    .insert(automationSettings)
    .values({
      organizationId,
      autoGenerateDrafts
    })
    .onConflictDoUpdate({
      target: automationSettings.organizationId,
      set: {
        autoGenerateDrafts,
        updatedAt: new Date()
      }
    });

  return {
    autoGenerateDrafts
  };
}
