import 'server-only';

import { and, eq } from 'drizzle-orm';
import { db } from '@/lib/db/drizzle';
import {
  automationSettings,
  locations,
  reviews
} from '@/lib/db/schema';
import { generateDraftForReview } from '@/lib/reviews/generate-draft';
import type {
  NormalizedProviderReview
} from '@/lib/integrations/providers/types';

export type IngestReviewInput = NormalizedProviderReview & {
  organizationId: number;
  locationId: number;
};

export type IngestReviewResult = {
  reviewId: number;
  created: boolean;
  draftGenerated: boolean;
};

export async function ingestReview(
  input: IngestReviewInput
): Promise<IngestReviewResult> {
  if (
    !Number.isInteger(input.rating) ||
    input.rating < 1 ||
    input.rating > 5
  ) {
    throw new Error('Invalid review rating');
  }

  const [location] = await db
    .select({ id: locations.id })
    .from(locations)
    .where(
      and(
        eq(locations.id, input.locationId),
        eq(locations.organizationId, input.organizationId)
      )
    )
    .limit(1);

  if (!location) {
    throw new Error('Location not found');
  }

  const [review] = await db
    .insert(reviews)
    .values({
      organizationId: input.organizationId,
      locationId: input.locationId,
      provider: input.provider,
      externalId: input.externalId,
      authorName: input.authorName,
      authorInitials: input.authorInitials,
      rating: input.rating,
      content: input.content,
      receivedAt: input.receivedAt
    })
    .onConflictDoNothing({
      target: [
        reviews.organizationId,
        reviews.provider,
        reviews.externalId
      ]
    })
    .returning({ id: reviews.id });

  if (!review) {
    const [existingReview] = await db
      .select({ id: reviews.id })
      .from(reviews)
      .where(
        and(
          eq(reviews.organizationId, input.organizationId),
          eq(reviews.provider, input.provider),
          eq(reviews.externalId, input.externalId)
        )
      )
      .limit(1);

    if (!existingReview) {
      throw new Error('Could not resolve existing review');
    }

    return {
      reviewId: existingReview.id,
      created: false,
      draftGenerated: false
    };
  }

  const [settings] = await db
    .select({
      autoGenerateDrafts: automationSettings.autoGenerateDrafts
    })
    .from(automationSettings)
    .where(
      eq(
        automationSettings.organizationId,
        input.organizationId
      )
    )
    .limit(1);

  if (!settings?.autoGenerateDrafts) {
    return {
      reviewId: review.id,
      created: true,
      draftGenerated: false
    };
  }

  try {
    await generateDraftForReview(
      input.organizationId,
      review.id
    );

    return {
      reviewId: review.id,
      created: true,
      draftGenerated: true
    };
  } catch (error) {
    console.error(
      'Automatic review draft generation failed',
      error instanceof Error ? error.message : 'Unknown error'
    );

    return {
      reviewId: review.id,
      created: true,
      draftGenerated: false
    };
  }
}
