import { and, eq } from 'drizzle-orm';
import type { createWorkerDb } from '@/lib/db/worker';
import {
  automationSettings,
  jobs,
  locations,
  reviews
} from '@/lib/db/schema';
import type {
  NormalizedProviderReview
} from '@/lib/integrations/providers/types';

export type IngestReviewInput = NormalizedProviderReview & {
  organizationId: number;
  locationId: number;
};

export type IngestReviewResult = {
  reviewId: number;
  created: boolean;
  draftQueued: boolean;
};

export async function ingestReview(
  db: ReturnType<typeof createWorkerDb>['db'],
  input: IngestReviewInput
): Promise<IngestReviewResult> {
  if (
    !Number.isInteger(input.rating) ||
    input.rating < 1 ||
    input.rating > 5
  ) {
    throw new Error('Invalid review rating');
  }

  return db.transaction(async (tx) => {
    const [location] = await tx
      .select({ id: locations.id })
      .from(locations)
      .where(
        and(
          eq(locations.id, input.locationId),
          eq(locations.organizationId, input.organizationId)
        )
      )
      .limit(1);

    if (!location) {
      throw new Error('Location not found');
    }

    const [review] = await tx
      .insert(reviews)
      .values({
        organizationId: input.organizationId,
        locationId: input.locationId,
        provider: input.provider,
        externalId: input.externalId,
        authorName: input.authorName,
        authorInitials: input.authorInitials,
        rating: input.rating,
        content: input.content,
        receivedAt: input.receivedAt
      })
      .onConflictDoNothing({
        target: [
          reviews.organizationId,
          reviews.provider,
          reviews.externalId
        ]
      })
      .returning({ id: reviews.id });

    if (!review) {
      const [existingReview] = await tx
        .select({ id: reviews.id })
        .from(reviews)
        .where(
          and(
            eq(reviews.organizationId, input.organizationId),
            eq(reviews.provider, input.provider),
            eq(reviews.externalId, input.externalId)
          )
        )
        .limit(1);

      if (!existingReview) {
        throw new Error('Could not resolve existing review');
      }

      return {
        reviewId: existingReview.id,
        created: false,
        draftQueued: false
      };
    }

    const [settings] = await tx
      .select({
        autoGenerateDrafts: automationSettings.autoGenerateDrafts
      })
      .from(automationSettings)
      .where(
        eq(
          automationSettings.organizationId,
          input.organizationId
        )
      )
      .limit(1);

    if (!settings?.autoGenerateDrafts) {
      return {
        reviewId: review.id,
        created: true,
        draftQueued: false
      };
    }

    await tx
      .insert(jobs)
      .values({
        organizationId: input.organizationId,
        type: 'generate-ai-draft',
        dedupeKey: `generate-ai-draft:${input.organizationId}:${review.id}`,
        payload: {
          reviewId: review.id
        }
      });

    return {
      reviewId: review.id,
      created: true,
      draftQueued: true
    };
  });
}
