import assert from 'node:assert/strict';
import test from 'node:test';

import { eq } from 'drizzle-orm';

import { createWorkerDb } from '@/lib/db/worker';
import {
  automationSettings,
  jobs,
  locations,
  organizations,
  reviews
} from '@/lib/db/schema';
import { ingestReview } from '@/lib/reviews/ingest';

test(
  'ingestReview updates existing reviews without duplicating draft jobs',
  async () => {
    const workerDb = createWorkerDb();
    let organizationId: number | null = null;

    const suffix =
      `${Date.now()}-${Math.random().toString(36).slice(2)}`;

    try {
      const [organization] = await workerDb.db
        .insert(organizations)
        .values({
          name: 'Review Ingest Test',
          slug: `review-ingest-${suffix}`
        })
        .returning({
          id: organizations.id
        });

      assert.ok(organization);
      organizationId = organization.id;

      await workerDb.db
        .insert(automationSettings)
        .values({
          organizationId,
          autoGenerateDrafts: true
        });

      const [location] = await workerDb.db
        .insert(locations)
        .values({
          organizationId,
          name: 'Review Ingest Location',
          provider: 'google',
          externalId: `location-${suffix}`
        })
        .returning({
          id: locations.id
        });

      assert.ok(location);

      const first = await ingestReview(workerDb.db, {
        organizationId,
        locationId: location.id,
        provider: 'google',
        externalId: `review-${suffix}`,
        authorName: 'Original Name',
        authorInitials: 'ON',
        rating: 3,
        content: 'Original review',
        receivedAt: new Date('2026-09-01T10:00:00Z')
      });

      assert.equal(first.created, true);
      assert.equal(first.draftQueued, true);

      const firstJobs = await workerDb.db
        .select({
          id: jobs.id,
          type: jobs.type,
          payload: jobs.payload,
          dedupeKey: jobs.dedupeKey
        })
        .from(jobs)
        .where(eq(jobs.organizationId, organizationId));

      assert.equal(firstJobs.length, 1);
      assert.equal(firstJobs[0]?.type, 'generate-ai-draft');
      assert.deepEqual(firstJobs[0]?.payload, {
        reviewId: first.reviewId
      });
      assert.equal(
        firstJobs[0]?.dedupeKey,
        `generate-ai-draft:${organizationId}:${first.reviewId}`
      );

      const second = await ingestReview(workerDb.db, {
        organizationId,
        locationId: location.id,
        provider: 'google',
        externalId: `review-${suffix}`,
        authorName: 'Updated Name',
        authorInitials: 'UN',
        rating: 5,
        content: 'Updated review',
        receivedAt: new Date('2026-09-01T10:00:00Z')
      });

      assert.equal(second.reviewId, first.reviewId);
      assert.equal(second.created, false);
      assert.equal(second.draftQueued, false);

      const [stored] = await workerDb.db
        .select({
          authorName: reviews.authorName,
          authorInitials: reviews.authorInitials,
          rating: reviews.rating,
          content: reviews.content,
          receivedAt: reviews.receivedAt
        })
        .from(reviews)
        .where(eq(reviews.id, first.reviewId))
        .limit(1);

      assert.ok(stored);
      assert.equal(stored.authorName, 'Updated Name');
      assert.equal(stored.authorInitials, 'UN');
      assert.equal(stored.rating, 5);
      assert.equal(stored.content, 'Updated review');
      assert.equal(
        stored.receivedAt.getTime(),
        new Date('2026-09-01T10:00:00Z').getTime()
      );

      const finalJobs = await workerDb.db
        .select({
          id: jobs.id
        })
        .from(jobs)
        .where(eq(jobs.organizationId, organizationId));

      assert.equal(finalJobs.length, 1);
    } finally {
      if (organizationId !== null) {
        await workerDb.db
          .delete(organizations)
          .where(eq(organizations.id, organizationId));
      }

      await workerDb.client.end();
    }
  }
);
