'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db/drizzle';
import { automationSettings } from '@/lib/db/schema';
import { getOrganizationForUser } from '@/lib/db/queries';

export async function setAutoGenerateDrafts(
  enabled: boolean
) {
  const membership = await getOrganizationForUser();

  if (!membership) {
    redirect('/sign-in');
  }

  const organizationId = membership.organization.id;

  await db
    .insert(automationSettings)
    .values({
      organizationId,
      autoGenerateDrafts: enabled
    })
    .onConflictDoUpdate({
      target: automationSettings.organizationId,
      set: {
        autoGenerateDrafts: enabled,
        updatedAt: new Date()
      }
    });

  revalidatePath('/automations');
}
