'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';

import { saveAutomations } from '@/lib/api/server';

export async function setAutoGenerateDrafts(
  enabled: boolean
) {
  const result = await saveAutomations(enabled);

  if (
    !result.success &&
    result.error === 'Unauthorized'
  ) {
    redirect('/sign-in');
  }

  if (!result.success) {
    throw new Error(result.error);
  }

  revalidatePath('/automations');
}
