import { redirect } from 'next/navigation';
import { Bot, CheckCircle2, ShieldCheck } from 'lucide-react';
import { AutomationToggle } from '@/components/revo/automation-toggle';
import { getAutomations } from '@/lib/api/server';

export default async function AutomationsPage() {
  const result = await getAutomations();

  if (
    !result.success &&
    result.error === 'Unauthorized'
  ) {
    redirect('/sign-in');
  }

  if (!result.success) {
    throw new Error(result.error);
  }

  const enabled =
    result.settings.autoGenerateDrafts;

  return (
    <div className="h-full overflow-y-auto bg-background">
      <header className="border-b px-6 py-5">
        <h1 className="text-lg font-semibold tracking-[-0.025em]">
          Automations
        </h1>

        <p className="mt-1 text-xs text-muted-foreground">
          Control how Revo assists with incoming reviews.
        </p>
      </header>

      <div className="mx-auto max-w-3xl px-6 py-8">
        <section>
          <h2 className="text-sm font-semibold">
            Response automation
          </h2>

          <p className="mt-1 text-xs text-muted-foreground">
            Automate repetitive work while keeping final responses
            under human control.
          </p>

          <div className="mt-4 rounded-lg border bg-surface">
            <div className="flex items-start justify-between gap-6 px-5 py-5">
              <div className="flex min-w-0 gap-3">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md border bg-background">
                  <Bot className="h-4 w-4 text-muted-foreground" />
                </div>

                <div>
                  <div className="text-[13px] font-medium">
                    Automatically generate AI draft responses
                  </div>

                  <p className="mt-1 max-w-xl text-xs leading-5 text-muted-foreground">
                    When a new review arrives, Revo can prepare a
                    response using your Brand Voice. The response
                    remains a draft until someone reviews it.
                  </p>
                </div>
              </div>

              <AutomationToggle initialEnabled={enabled} />
            </div>

            <div className="border-t px-5 py-4">
              <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
                <ShieldCheck className="h-3.5 w-3.5 shrink-0" />
                Revo will never automatically approve or publish a
                response.
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 border-t pt-8">
          <h2 className="text-sm font-semibold">
            Workflow
          </h2>

          <div className="mt-4 space-y-3">
            {[
              'A new review is received',
              'Revo generates an on-brand draft',
              'A person reviews and approves the response',
              'The approved response can be published'
            ].map((step, index) => (
              <div
                key={step}
                className="flex items-center gap-3 text-xs"
              >
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border bg-surface text-[10px] font-medium">
                  {index + 1}
                </div>

                <span>{step}</span>

                {index === 2 && (
                  <span className="ml-1 flex items-center gap-1 text-[10px] text-muted-foreground">
                    <CheckCircle2 className="h-3 w-3" />
                    Human approval
                  </span>
                )}
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
