'use client';

import { useState, useTransition } from 'react';
import { setAutoGenerateDrafts } from '@/app/(dashboard)/automations/actions';

export function AutomationToggle({
  initialEnabled
}: {
  initialEnabled: boolean;
}) {
  const [enabled, setEnabled] = useState(initialEnabled);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function toggle() {
    const previous = enabled;
    const next = !previous;

    setEnabled(next);
    setError(null);

    startTransition(async () => {
      try {
        await setAutoGenerateDrafts(next);
      } catch (error) {
        console.error('Failed to update automation setting', error);
        setEnabled(previous);
        setError('Could not save this setting.');
      }
    });
  }

  return (
    <div className="flex flex-col items-end gap-2">
      <button
        type="button"
        role="switch"
        aria-checked={enabled}
        aria-label="Automatically generate AI draft responses"
        disabled={isPending}
        onClick={toggle}
        className={[
          'relative h-5 w-9 shrink-0 rounded-full transition-colors',
          enabled ? 'bg-foreground' : 'bg-muted',
          isPending ? 'cursor-wait opacity-60' : ''
        ].join(' ')}
      >
        <span
          className={[
            'absolute top-0.5 h-4 w-4 rounded-full bg-background shadow-sm transition-transform',
            enabled ? 'translate-x-[18px]' : 'translate-x-0.5'
          ].join(' ')}
        />
      </button>

      {error && (
        <span className="text-[10px] text-destructive">
          {error}
        </span>
      )}
    </div>
  );
}
